name: Build on LP and run spread tests

on:
  pull_request:
    branches:
      - main

concurrency:
  group: lp-build-${{ github.head_ref || github.run_id }}-${{ github.event_name }}
  # TODO: how to cancel LP job?
  cancel-in-progress: true

jobs:
  build:
    timeout-minutes: 720
    # self-hosted runner so we can access gce from external repos
    runs-on: self-hosted
    steps:
      - name: Build and test
        env:
          LP_CREDENTIALS: ${{ secrets.LP_CREDENTIALS }}
        uses: snapcore/system-snaps-cicd-tools/action-test@main
        with:
          # add riscv64 once we have a core24 snap for it, see
          # https://launchpad.net/~ubuntu-core-service/+snap/core24
          architectures: arm64,amd64,armhf
          spread_suites: "google-nested:"
